### PR TITLE
failing test for #16

### PR DESCRIPTION
**Pull request by Rich-Harris**

### CODE REVIEW

**Comment by Conduitry** [comment]
I think this is good to go now. Number patching should be Bug Free (tm) now - including handling for signs of numbers changing or staying the same, and including numbers between -1 and 1 with no 0 before the decimal point staying in that range or moving out of it, and including signed numbers not in base 10. I also added octal support while I was at it.

I didn't deal with any exponential notation stuff. There's possibly some nicer way we could patch those in some cases, but I'm not sure what it would be exactly, and I don't think just letting `String(value)` worry about that will cause any actual bugs.

**Comment by Conduitry** [comment]
Gah, not ready to go. Just realized that this doesn't handle non-base-10 integers turning into non-integer values. Why this would happen in practice I have no idea, but that doesn't mean we should have malformed output.

**Comment by Conduitry** [comment]
Okay NOW it is Probably Bug Free.

**Comment by Rich-Harris** [comment]
Probably Bug Free is as good as software gets. Thanks — released 1.0.9

**Pull request merged**
